# Generated by Django 2.2.3 on 2019-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190825_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
