version: '3'

services:

    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
        - /home/cosmo/db_data/db.sqlite3:/code/db.sqlite3
      ports:
        - "8000:8000"